### ISSUE TITLE
Remove `.gitattributes` (for now)

### ISSUE THREAD

**Issue by ghost** [healeycodes/crane-search#2]
I decided that a very minor change was not worthy of having its own pull request, so the suggestion is here instead.
I know the project is primarily written in Go, but as you know, there are some shell scripts that are vital to the functionality of the code. The suggestion? Simply remove the `.gitattributes` file. When I tested it in a fork, the `dist` folder was vendored; but if that is still a concern, then you can add `dist/* linguist-vendored`.

**Comment by healeycodes** [comment]
Thanks for the suggestion @F1nx 

Fixed in https://github.com/healeycodes/crane-search/commit/1a8e47b770d6f0882dd70cdf9d1b210f13cb432c 🚀
